# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Green Wallets"
client_id = "8a836175da40536e65b7fcc6b5fa4e10"
application_url = "https://expenditures-districts-were-metallica.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,read_discounts,read_products,write_products"

[auth]
redirect_urls = [
  "https://expenditures-districts-were-metallica.trycloudflare.com/auth/callback",
  "https://expenditures-districts-were-metallica.trycloudflare.com/auth/shopify/callback",
  "https://expenditures-districts-were-metallica.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "green-wallet-test.myshopify.com"
